name: {{workflow_name}}

{{on_block}}

{{permissions_block}}

{{env_block}}

jobs:
  agentic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/.local/share/R
          key: ${{ runner.os }}-r-pkgs-${{ hashFiles('**/DESCRIPTION') }}
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install pak
        run: install.packages('pak', repos = 'https://cloud.r-project.org')
      - name: Install agentic and dependencies
        run: Rscript -e "pak::pak('agentic', dependencies = TRUE)"
      - name: Run agentic script
        run: Rscript .github/agentic/{{workflow_name}}.R 
