name: {{workflow_name}}

{{on_block}}

{{permissions_block}}

{{env_block}}

jobs:
  agentic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      - name: Install system dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev
      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/.local/share/R
          key: ${{ runner.os }}-r-pkgs-${{ hashFiles('**/DESCRIPTION') }}
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
      - name: Install pak
        run: |
          Rscript -e "install.packages('pak', repos = c(CRAN = 'https://packagemanager.posit.co/cran/__linux__/jammy/latest'))"
      - name: Install agentic
        run: |
          Rscript -e 'options(repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/jammy/latest"));pak::pak("cynkra/agentic")'
      - name: Install local package
        run: |
          Rscript -e 'options(repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/jammy/latest"));pak::pak(".")'

      - name: Run agentic script
        run: |
          Rscript .github/agentic/{{workflow_name}}.R 
